FROM python:3.10

COPY . .
RUN pip install pipenv
EXPOSE 8081
CMD ["pipenv", "run", "int"]

# COPY requirements.txt .
# COPY .env .env
# RUN pip install -r requirements.txt
# EXPOSE 80
# COPY ./src /src
# # ENV APIENV integration
# CMD ["python", "src/run.py"]